name: Init Rails Microservice

on: [create]
  # workflow_dispatch:
  #   inputs:
  #     repo_tag:
  #       description: 'What is the name of your new repository?'
  #       required: true
  #       type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout repo 
      uses: actions/checkout@v2
    - name: Ruby Install
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - name: Rails Install
      run: gem install rails
    - name: Generate new Rails project
      run: rails new ${{ github.event.repository.name }} --minimal --api d=postgresql
    - name: Bundle Install
      run: bundle install
    - name: Commit changes
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
  debug:
    name: Debug Contexts
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |-
          cat << 'EOF_QUOTED'
          ${{ toJSON(github) }}
          EOF_QUOTED
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump steps context
        run: echo '${{ toJSON(steps) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump strategy context
        run: echo '${{ toJSON(strategy) }}'
      - name: Dump matrix context
        run: echo '${{ toJSON(matrix) }}'
      - name: Dump inputs/workflow call context
        run: echo '${{ toJSON(inputs) }}'
